<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-93VLQEKH" failures="0" tests="1" name="Spothopper.QA.TestCases.ChatGptIntegrationTest" time="17.401" errors="1" timestamp="2024-12-26T12:10:50 CET" skipped="0">
  <testcase classname="Spothopper.QA.TestCases.ChatGptIntegrationTest" name="sinchronizeChanges" time="17.401">
    <error message="Unexpected code: Response{protocol=h2, code=401, message=, url=https://api.openai.com/v1/chat/completions}" type="java.io.IOException">
      <![CDATA[java.io.IOException: Unexpected code: Response{protocol=h2, code=401, message=, url=https://api.openai.com/v1/chat/completions}
at Spothopper.QA.PageObjects.ChatGptIntegrationPage.generateChatGptMessage(ChatGptIntegrationPage.java:142)
at Spothopper.QA.TestCases.ChatGptIntegrationTest.sinchronizeChanges(ChatGptIntegrationTest.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- sinchronizeChanges -->
  <system-out/>
</testsuite> <!-- Spothopper.QA.TestCases.ChatGptIntegrationTest -->
